name: Compute Python min/max from pyproject
runs:
  using: "composite"
  steps:
    - id: compute
      shell: bash
      run: |
        python - <<'PY' > compute.json
from scripts.lib.python_versions import json_blob
print(json_blob())
PY
        echo "min=$(jq -r .min compute.json)" >> "$GITHUB_OUTPUT"
        echo "max=$(jq -r .max compute.json)" >> "$GITHUB_OUTPUT"
        if [ "$(jq -r .min compute.json)" = "$(jq -r .max compute.json)" ]; then
          echo "matrix=[\"$(jq -r .min compute.json)\"]" >> "$GITHUB_OUTPUT"
        else
          echo "matrix=[\"$(jq -r .min compute.json)\", \"$(jq -r .max compute.json)\"]" >> "$GITHUB_OUTPUT"
        fi
outputs:
  min:
    value: ${{ steps.compute.outputs.min }}
  max:
    value: ${{ steps.compute.outputs.max }}
  matrix:
    value: ${{ steps.compute.outputs.matrix }}

