ci:
    autoupdate_schedule: 'monthly'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit  # Ruff version.
    rev: "v0.12.9"
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'
      - id: check-yaml
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [
          "--ignore-words",
          ".codespellignore",
        ]

  - repo: https://github.com/DavidAnson/markdownlint-cli2  # For formatting markdown for documentation
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        args: [
          "--fix",
          "--config",
          ".markdownlint.json",
        ]
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'

  - repo: https://github.com/jsh9/pydoclint  # For checking docstrings
    rev: 0.6.6
    hooks:
      - id: pydoclint
        args: [--style=numpy, --skip-checking-raises=True, --allow-init-docstring=True]
        exclude: '^\{\{cookiecutter\.repo_name\}\}/'

  # Local validations specific to this template repository
  - repo: local
    hooks:
      - id: validate-template
        name: Validate template tokens and workflows
        entry: python scripts/validate_template.py
        language: system
        pass_filenames: false

  # Lint root repo GitHub Actions workflows
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: '^\.github/workflows/.*\.ya?ml$'
