site_name: Pythonic Template
site_url: https://adamamer20.github.io/pythonic-template/
site_author: Adam Amer
site_description: A modern, comprehensive Cookiecutter template for Python projects following best practices

repo_name: adamamer20/pythonic-template
repo_url: https://github.com/adamamer20/pythonic-template

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Configuration: getting-started/configuration.md
      - Generated Project: getting-started/generated-project.md
  - Features:
      - Modern Stack: features/modern-stack.md
      - Quality Assurance: features/quality-assurance.md
      - Documentation: features/documentation.md
      - DevOps: features/devops.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Release Process: development/release-process.md
  - Reference:
      - Template Variables: reference/template-variables.md
      - Project Structure: reference/project-structure.md
      - Best Practices: reference/best-practices.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adamamer20
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/adamamer20/

copyright: Copyright &copy; 2025 Adam Amer
