blank_issues_enabled: true
contact_links:
  - name: Discussions/Questions etc
    url: https://github.com/adamamer20/pythonic-template/discussions
    about: Discuss pythonic-template, ask questions, do discussions, share ideas, and showcase your projects



