name: Publish

on:
  release:
    types: [published]

env:
  FORCE_COLOR: 1

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      py-max: {{ '${{ steps.out.outputs.max }}' }}
    steps:
      - uses: actions/checkout@v4
      - id: out
        uses: ./.github/actions/compute-python

  publish:
    needs: compute
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/{{ cookiecutter.package_name }}
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv & select Python (max)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: {{ '${{ needs.compute.outputs.py-max }}' }}

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
