name: build

on:
  push:
    branches:
    - main
    - 'release**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

# This will cancel previous run if a newer job that obsoletes the said previous
# run, is started.
# Based on https://github.com/zulip/zulip/commit/4a11642cee3c8aec976d305d51a86e60e5d70522
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      py-min: ${{ steps.out.outputs.min }}
      py-max: ${{ steps.out.outputs.max }}
      py-matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: out
        uses: ./.github/actions/compute-python

  build:
    needs: compute
    runs-on: ${{ matrix.os }}-latest
    # We need an explicit timeout because sometimes the batch_runner test never
    # completes.
    timeout-minutes: 6
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ${{ fromJson(needs.compute.outputs.py-matrix) }}

    steps:
    - uses: actions/checkout@v4
    - name: Install uv & select Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Sync environment (dev dependencies)
      run: |
        uv sync --all-extras
    - name: Test with pytest
      run: uv run pytest --durations=10 --cov=hooks --cov-branch tests/ --cov-report=xml
    - if: matrix.os == 'ubuntu'
      name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
