name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for Trusted Publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (manage Python)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          manage-python: true
          python-version: '3.12'

      - name: Sync environment
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest -q

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        if: ${{ !github.event.release.prerelease }}
        uses: pypa/gh-action-pypi-publish@release/v1
