name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for Trusted Publishing

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      py-min: ${{ steps.out.outputs.min }}
      py-max: ${{ steps.out.outputs.max }}
      py-matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: out
        uses: ./.github/actions/compute-python

  build-and-publish:
    needs: compute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv & select Python (max)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ needs.compute.outputs.py-max }}

      - name: Sync environment
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest -q

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        if: ${{ !github.event.release.prerelease }}
        uses: pypa/gh-action-pypi-publish@release/v1
